pool:
    vmImage: windows-2019
steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.15.1
      displayName: Install Node.js
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: Sonar
        organization: project-initium
        scannerMode: MSBuild
        projectKey: initium-portal
        extraProperties: |
          sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          sonar.exclusions=**\Resources\Themes\**
    - task: Cake@0
      inputs:
        script: Build/build-master.cake
        target: Default
        verbosity: Verbose
    - task: PublishTestResults@2
      displayName: Publish Test Results coverage/xunit-report.xml
      inputs:
        testResultsFormat: XUnit
        testResultsFiles: '**/xunit-report.xml'
      continueOnError: true
    - task: PublishCodeCoverageResults@1
      displayName: Publish code coverage from coverage/cobertura-coverage.xml
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: build/build-artifacts/cover/coverage.cobertura.xml
      continueOnError: true 
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'Build/build-artifacts/release/template.zip'
        ArtifactName: 'template'
        publishLocation: 'Container'