pool:
    vmImage: windows-2019
steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.15.1
      displayName: Install Node.js
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: Sonar
        organization: project-initium
        scannerMode: MSBuild
        projectKey: initium-portal
        extraProperties: |
          sonar.modules=server,client  
          server.sonar.projectName=Server
          server.sonar.cs.opencover.reportsPaths=build/build-artifacts/cover/server/coverage.cobertura.xml
          server.sonar.exclusions=**\Resources\Themes\**
          client.sonar.typescript.lcov.reportPaths=build/build-artifacts/cover/client/lcov.info
          client.sonar.projectName=Client
          client.sonar.sources=Source/Initium.Portal.Web/Resources/Scripts
    - task: Cake@0
      inputs:
        script: Build/build-master.cake
        target: Default
        verbosity: Verbose
    - task: PublishTestResults@2
      displayName: Publish server test results
      inputs:
        testResultsFormat: XUnit
        testResultsFiles: 'build/build-artifacts/cover/server/xunit-report.xml'
      continueOnError: true
    - task: PublishTestResults@2
      displayName: 'Publish client test results'
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: 'build/build-artifacts/cover/client/junit-report.xml'
    - task: PublishCodeCoverageResults@1
      displayName: Publish server code coverage
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: 'build/build-artifacts/cover/server/coverage.cobertura.xml'
      continueOnError: true 
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish client code coverage'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: 'build/build-artifacts/cover/client/cobertura-coverage.xml'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'Build/build-artifacts/release/template.zip'
        ArtifactName: 'template'
        publishLocation: 'Container'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))